### ISSUE TITLE
"All Items" needs to function like a section

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#10]
"All Items" needs to function like a section. This means the following:
- It should appear in the sections list (if they have it turned on with the toggle switch)
- The app owner should be able to assign a list image to it
- The app owner should be able to enter it and add items inside of it. This is where all of the items should exist since it should be mandatory that the items exist inside of it. This way we prevent there from being any orphan entries.
- The app user should be able to step into it like they would a section

**Comment by vineetasharma** [comment]
@nathankeating  Fixed the Issue. Please check this.

**Comment by nathankeating** [comment]
Fixed:
- The app owner should be able to assign a list image to it
- The app owner should be able to enter it and add items inside of it.

Not Fixed
- It should appear in the sections list in the app (if they have it turned on with the toggle switch)
- This is where all of the items should exist since it should be mandatory that the items exist inside of it. This way we prevent there from being any orphan entries.
- The app user should be able to step into it like they would a section

**Comment by vineetasharma** [comment]
Fixed the issue:
1. It should appear in the sections list in the app (if they have it turned on with the toggle switch).
2. The app user should be able to step into it like they would a section
