### ISSUE TITLE
The editor is blank when you first enter the plugin

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#12]
The editor is blank when you first enter the plugin

**Comment by nathankeating** [comment]
I think this might only happen when you access it from the Active Plugins page.

<img width="1440" alt="screen shot 2015-10-13 at 8 46 41 pm" src="https://cloud.githubusercontent.com/assets/6145369/10474431/84bfd150-71eb-11e5-9337-02c1605bee9e.png">

**Comment by ianblair44** [comment]
@nathankeating is this still happening? This would be on our side.
