### ISSUE TITLE
Distance indicator not working on the item details page

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#14]
The distance indicator is not working on the item details page.

All of the items show 324mi instead of the actual miles or kilometers (whichever is selected) to the location

<img width="381" alt="screen shot 2015-10-13 at 8 50 05 pm" src="https://cloud.githubusercontent.com/assets/6145369/10474484/186c08b0-71ec-11e5-812a-4507a679a030.png">

**Comment by vineetasharma** [comment]
Fixed the issue. Please check this.

**Comment by nathankeating** [comment]
Cannot test because the item list and item details do not load. See image:

<img width="1440" alt="screen shot 2015-10-16 at 5 32 16 pm" src="https://cloud.githubusercontent.com/assets/6145369/10555930/e6e2583e-742b-11e5-9b8f-5b4cf4b65e65.png">

**Comment by nathankeating** [comment]
confirmed
