### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#15]
Navigating through the plugin flickers a lot. It seems as though forward/backward transitions have not been implemented.

**Comment by vineetasharma** [comment]
@nathankeating  Please explain it.

**Comment by ianblair44** [comment]
We are going to be implementing transitions in all the plugins soon.

**Comment by vineetasharma** [comment]
@nathankeating Fixed the issue. Please Check this.

**Comment by nathankeating** [comment]
@ianblair44 Are you seeing transitions? I do not see any transitions on my phone

**Comment by nathankeating** [comment]
I don't see them on the CP emulator either

**Comment by nathankeating** [comment]
Not fixed. Moving to main repo
