### ISSUE TITLE
Section Title field should be above the Main Image when editing a section

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#17]
Section Title field should be above the Main Image when editing a section

**Comment by nathankeating** [comment]
<img width="746" alt="screen shot 2015-10-13 at 8 54 53 pm" src="https://cloud.githubusercontent.com/assets/6145369/10474545/ac3c77be-71ec-11e5-9a77-11509f38e683.png">

**Comment by kmtabish** [comment]
Fixed. Please review.

**Comment by nathankeating** [comment]
Confirmed
