### ISSUE TITLE
Delete item popup text

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#18]
When deleting an item entry inside a section, the delete item popup should say
- Title: Delete Item?
- Are you sure you want to delete this item?

**Comment by kmtabish** [comment]
Fixed. Please review.

**Comment by nathankeating** [comment]
Please also change "Remove" to "Delete" on the bottom right button

**Comment by vineetasharma** [comment]
Fixed. Please Check it.

**Comment by nathankeating** [comment]
"Delete" is spelled incorrectly on the delete button on the popup. It's currently spelled "Detele"

**Comment by vineetasharma** [comment]
@nathankeating  Fixed the Issue. Please review it.

**Comment by nathankeating** [comment]
confirmed
