### ISSUE TITLE
Item list scrolling in editor

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#19]
The item list should not scroll, but rather keep extending down. Otherwise, the user only sees a few items 

<img width="1440" alt="screen shot 2015-10-13 at 8 59 42 pm" src="https://cloud.githubusercontent.com/assets/6145369/10474602/5c4d9eee-71ed-11e5-91cd-bb15be960e71.png">

**Comment by vineetasharma** [comment]
@nathankeating  If we have 1000 items then need to show all items without scroll in this case?

**Comment by ianblair44** [comment]
Let the body of the content section extend down the page.

**Comment by vineetasharma** [comment]
@nathankeating  Fixed the Issue. Please Check this.

**Comment by nathankeating** [comment]
Fixed on item lists.

Please implement this in the section list as well.

Also, please keep in mind that if the user does have a large number of entries, that they need to lazy load on the CP and on the App

**Comment by vineetasharma** [comment]
@nathankeating  Fixed. Please Check.

**Comment by nathankeating** [comment]
Confirmed
