### ISSUE TITLE
Clickable area for sections and items on lists and the map

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#24]
The entire section/item content (image, title, summary) should be clickable so that the user can click anywhere on it to go in. Currently, only the item title is clickable.

<img width="391" alt="screen shot 2015-10-13 at 9 07 06 pm" src="https://cloud.githubusercontent.com/assets/6145369/10474679/66f3c02a-71ee-11e5-9111-7994f335d0c5.png">

**Comment by kmtabish** [comment]
Fixed. Please review.

**Comment by nathankeating** [comment]
confirmed
