### ISSUE TITLE
Clicking an item in the app does not take you to the correct item

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#25]
Clicking an item in the app does not take you to the correct item

In this image, I clicked on the item called "Petco Park"
<img width="390" alt="screen shot 2015-10-13 at 9 09 31 pm" src="https://cloud.githubusercontent.com/assets/6145369/10474717/dd2250fe-71ee-11e5-93b4-78559150ca20.png">

Instead, it took me to Balboa Park:
<img width="382" alt="screen shot 2015-10-13 at 9 09 34 pm" src="https://cloud.githubusercontent.com/assets/6145369/10474719/e4f469de-71ee-11e5-9d81-d266f409f1be.png">

**Comment by lakshaydulani** [comment]
Fixed.

**Comment by nathankeating** [comment]
confirmed
