### ISSUE TITLE
Appearance of duplicate entries in the app

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#26]
Clicking back on the nav bar in the emulator displays duplicates of item entries in the app. It does not actually, however, create duplicate items on the editor side.

<img width="390" alt="screen shot 2015-10-13 at 9 25 40 pm" src="https://cloud.githubusercontent.com/assets/6145369/10474858/f8418cb8-71f0-11e5-922d-a89f4b7947f5.png">

**Comment by vineetasharma** [comment]
Fixed the issue. Please check this.

**Comment by nathankeating** [comment]
I believe this to be confirmed...
