### ISSUE TITLE
“Filter” text on filter button not there

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#28]
“Filter” text on filter button not there

<img width="379" alt="screen shot 2015-10-13 at 9 28 08 pm" src="https://cloud.githubusercontent.com/assets/6145369/10474871/5756e5ae-71f1-11e5-92b9-c7277c1d98be.png">

**Comment by kmtabish** [comment]
This issue is fixed now.

**Comment by nathankeating** [comment]
confirmed
