### ISSUE TITLE
Map button is where the locator button should be.

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#29]
The map button is where the locator button should be. Instead, the map/list toggle button should be at the bottom next to filter on the left side

Here is the mockup (Ignore the "See All")
![map layout 1](https://cloud.githubusercontent.com/assets/6145369/10474908/cc377a5a-71f1-11e5-9921-1fde6fbfe323.png)

**Comment by lakshaydulani** [comment]
@nathankeating There is only a Filter button in the bottom. 
@JDM555 had told us that there wont be a Map button and the locator button will only be used to go to the maps layout (in addition to re fetching user's location), as well as See All button wont be there too.

**Comment by nathankeating** [comment]
On the bottom, there should be the "Map/List" and "Filter" buttons. The circular button should be the locator button where it will fetch the user's location.

You are correct that the "See All" button has been removed

**Comment by lakshaydulani** [comment]
Added the Map/List button. Please review.

**Comment by nathankeating** [comment]
Map/List button seems to toggle

To get the locator button to work, however, you have to either click on it multiple times or wait at least 4ish seconds

**Comment by lakshaydulani** [comment]
@nathankeating Please try on the latest buil. It is working fine.

**Comment by nathankeating** [comment]
Confirmed
