### ISSUE TITLE
Filtering for All Locations shows a bunch of duplicate entries.

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#31]
Filtering for All Locations shows a bunch of duplicate entries.

<img width="385" alt="screen shot 2015-10-13 at 9 44 29 pm" src="https://cloud.githubusercontent.com/assets/6145369/10475050/ad8e926c-71f3-11e5-8156-20ed1be76cb1.png">
<img width="400" alt="screen shot 2015-10-13 at 9 44 34 pm" src="https://cloud.githubusercontent.com/assets/6145369/10475052/af548d36-71f3-11e5-8a25-502ef9fe6b4c.png">
<img width="395" alt="screen shot 2015-10-13 at 9 45 03 pm" src="https://cloud.githubusercontent.com/assets/6145369/10475053/b15e783a-71f3-11e5-948d-187faecd3c2f.png">

**Comment by lakshaydulani** [comment]
Fixed. Please review.

**Comment by nathankeating** [comment]
Confirmed
