### ISSUE TITLE
All Items should be defaulted to on

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#42]
All Items should be defaulted to on

<img width="743" alt="screen shot 2015-10-13 at 10 39 24 pm" src="https://cloud.githubusercontent.com/assets/6145369/10475708/47ae439a-71fb-11e5-8e06-1a07592b4c6d.png">

**Comment by vineetasharma** [comment]
Fixed the issue. Please Check this.

**Comment by nathankeating** [comment]
Confirmed
