### ISSUE TITLE
Selecting new layouts issue

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#44]
App does not update immediately when a new layout is selected under design if the user is not on that part of the plugin. For example, if you are on the item list and when you change the section list layout, the section list layout will not update until you reload the page or navigate to another part of the plugin and then come back.

**Comment by vineetasharma** [comment]
@nathankeating  Fixed the Issue. Please review it.

**Comment by nathankeating** [comment]
Confirmed
