### ISSUE TITLE
White space at the bottom below the filter button

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#46]
There is about 100 pixels of white space at the bottom below the filter button.

This only occurs on the actual phone (I am running iOS 9). The CP emulator is fine.

Here is a screen shot. You might need to save and open the image to see what I'm referring to.
![img_8698](https://cloud.githubusercontent.com/assets/6145369/10556065/1315b984-742f-11e5-84e4-64932d3c0c78.PNG)

**Comment by lakshaydulani** [comment]
Fixed. Please review.
![a](https://cloud.githubusercontent.com/assets/1629056/10636422/5b7d339a-781d-11e5-9ec1-a58b798e7315.jpg)

**Comment by nathankeating** [comment]
Confirmed
