### ISSUE TITLE
Menu won't close

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/placesPlugin#51]
This is always like that and it wont' go down.

<img width="407" alt="screen shot 2015-10-21 at 9 56 09 am" src="https://cloud.githubusercontent.com/assets/2794086/10644741/10af4602-77df-11e5-859f-80fcbcc4d32c.png">

**Comment by lakshaydulani** [comment]
Fixed. Please review.

**Comment by lakshaydulani** [comment]
@JDM555 @ianblair44 The bottom menu doesnt stay at the bottom (it scrolls with the page) if the transitions css is applied. Please look into it.

**Comment by nathankeating** [comment]
@ianblair44 can you close this?
