### ISSUE TITLE
Bottom menu scrolls with the page (iPhone only)

### ISSUE THREAD

**Issue by lakshaydulani** [BuildFire/placesPlugin#56]
@JDM555 @ianblair44 
The bottom bar scrolls with the page when I checked on iPhone(5s and 6+) today. 
The bottom menu is working perfectly now on the android devices though. 
I think the issue is due to scroll fixes made for the iPhone. 
I removed the max-height for the div #scroll-infinite, as we talked about; But it didn't make any difference to the UI.

**Comment by nathankeating** [comment]
still in effect. moving to main repo

@ianblair44 Can you close?
