### ISSUE TITLE
No Carousel and WYSIWYG in Control Panel, but given in Widget screenshot

### ISSUE THREAD

**Issue by lakshaydulani** [BuildFire/placesPlugin#6]
![screenshot from 2015-09-22 21 57 01](https://cloud.githubusercontent.com/assets/1629056/10024551/518b7e3c-6175-11e5-96d6-9cfc3e80c43c.png)
 
In the above screenshot, there is no Carousel/WYSISYG component, but it is there in Section List Layout 1-1, 2-1 and 3-1  in the folder https://drive.google.com/drive/u/0/folders/0B28Ow-B0LzjlTGR3WlB1TlpiM0E

Please tell if the above components will be there in the plugin.

**Comment by ianblair44** [comment]
We will need to add it above bulk actions. Good catch.

**Comment by lakshaydulani** [comment]
Ok @ianblair44  I will add the Carousel/WYSIWYG above the bulk actions.
